version: '3'
services:
  usagedata:
    #    build: ./retrieve-usagedata-svc
    image: kos-mvp/usagedata
    environment:
      target.service.name: usagedata-db:8080
      spring.redis.host: redis
    ports:
     - "8080:8080"
    links:
     - usagedata-db
     - redis

  usagedata-db:
    #    build: ./retrieve-usagedata-db-svc
    image: kos-mvp/usagedata-db
    environment:
      target.service.name: manage-cache:8080
      POSTGRES_ENV_IP: postgres
      POSTGRES_ENV_PORT: 5432
      POSTGRES_ENV_DB: engage
    links:
     - manage-cache
     - postgres 

  manage-cache:
    #    build: ./redis-cache-manager
    image: kos-mvp/manage-cache
    environment: 
      spring.redis.host: redis
    links:
     - redis

  redis:
    image: "redis:alpine"

  postgres:
    image: postgres
    environment:
     - POSTGRES_DB=engage
     - POSTGRES_USER=kos_user
     - POSTGRES_PASSWORD=new1234!
     - POSTGRES_INITDB_ARGS=--encoding=UTF-8
    volumes:
      - data:/var/lib/postgresql/data
      # - ./data/data.sql:/docker-entrypoint-initdb.d/init.sql
volumes:
  data:
    external: true

